### ISSUE TITLE
Page printing issue

### ISSUE THREAD

**Issue by fqueau** [ibm-cloud-docs/openshift#100]
Hi is there an easy way to print the documentation so that it is well formatted ? 

I'm trying to print that page : https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-block

but doing so it is very badely formatted. 

Thanks.

**Comment by derekpoindexter** [comment]
Hi, thank you for the feedback. I also see formatting issues when trying to save this page as a PDF. I've opened an internal issue for our docs app team to look into the PDF print/export issue further. In the meantime, you can try printing the markdown source file from here - https://github.com/ibm-cloud-docs/openshift/blob/master/storage-block-vpc.md

Here' an example pdf generated from the GitHub preview.

[vpc-block-.md.pdf](https://github.com/ibm-cloud-docs/openshift/files/7936106/vpc-block-.md.pdf)
