### ISSUE TITLE
IBM Cloud does offer private LB

### ISSUE THREAD

**Issue by bikasprice** [ibm-cloud-docs/openshift#103]
I don't think this statement is correct:

What if I want to load balance workloads on the private network?

**IBM Cloud does not offer a load balancer service on the private network.** However, you can connect your cluster to a private load balancer that you host in your on-prem network by using one of the [supported VPN options](https://cloud.ibm.com/docs/containers?topic=containers-vpn). Make sure to expose your apps on the private network by using [Ingress](https://cloud.ibm.com/docs/openshift?topic=openshift-ingress-about-roks4), [routers](https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_routes), or [Network Load Balancers (NLBs)](https://cloud.ibm.com/docs/containers?topic=containers-loadbalancer-about), and use the private IP address in your VPN settings to connect your app to your on-prem network.

I think this should say IBM Cloud does not offer a **global** load balancer

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. We've updated this page. The change will be live with our next publish.
