### ISSUE TITLE
Incorrect log for ROKS 

### ISSUE THREAD

**Issue by frykshon** [ibm-cloud-docs/openshift#108]
In step 6 on https://cloud.ibm.com/docs/openshift?topic=openshift-debug-kube-nodes it currently references '/var/log/syslog' but there is no syslog in redhat OS, that's for ubuntu. In redhat the log is '/var/log/messages' Since ROKS is built on redhat OS the correct log should be the /var/log/messages log.

**Comment by yingyeliu** [comment]
Fixed. Thanks!
