### ISSUE TITLE
Important documentation was removed when the VPC SG & NACL information was separated into different pages

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/openshift#109]
When the information about the security group and network ACL information was in the same page, there was also a statement regarding the security group created automatically when a VPC cluster is created, named kube-<cluster_ID> .  There used to be a statement that that security group should never be deleted or modified in any way by customers.  It's a very important thing for customers to know.  But it's no longer there.  It appears to also no longer be present in the Kubernetes section of documentation.  Please add it back so we can point customers to it when they ask why they mustn't modify it.

**Comment by derekpoindexter** [comment]
Hey @john-d-burke, thanks for the feedback. We've just overhauled this page - the updates are live now - https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-security-group
