### ISSUE TITLE
oc commands do not work in latest oc client versions

### ISSUE THREAD

**Issue by mkulamarva** [ibm-cloud-docs/openshift#110]
In the below document 
https://cloud.ibm.com/docs/openshift?topic=openshift-webhooks_update

Step 1 has the deprecated oc command:
```
oc run webhook-test --generator=run-pod/v1 --image registry.ng.bluemix.net/armada-master/pause:3.2 -n ibm-system
Error: unknown flag: --generator
See 'oc run --help' for usage. 
```

instead the command can be updated as:
`oc run webhook-test --image registry.ng.bluemix.net/armada-master/pause:3.2 -n ibm-system`

Also, please verify the other oc commands as well for any changes with latest oc versions. Thank you.

**Comment by yingyeliu** [comment]
Fixed. Thanks for your feedback.
