### ISSUE TITLE
Private firewall links improvement/suggestion 

### ISSUE THREAD

**Issue by frykshon** [ibm-cloud-docs/openshift#111]
Summary:
I think it would help to change the links listed below from the main doc to the specific sections noted.

This is the doc in question:
https://cloud.ibm.com/docs/openshift?topic=openshift-firewall#firewall_private

On the private firewall section is says:

>Allow the appropriate IBM Cloud infrastructure private IP ranges. See [Backend (private) Network](https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-ibm-cloud-ip-ranges).

and:

>Allow the IBM Cloud infrastructure private IP ranges for all the [zones](https://cloud.ibm.com/docs/openshift?topic=openshift-regions-and-zones#locations) that you are using. Note: You must add the 166.8.0.0/14 and  161.26.0.0/16 IP ranges, the IP ranges for the dal01, dal10, wdc04 zones, and if your cluster is in the Europe geography, the ams01 zone. See [Service Network (on backend/private network)](https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-ibm-cloud-ip-ranges).

Both link to: 
>https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-ibm-cloud-ip-ranges

It would help if the first one linked straight to the subsection:

>https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-ibm-cloud-ip-ranges#back-end-network

And for the second, the zone part is right but the service network could point straight to:
>https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-ibm-cloud-ip-ranges#service-network

**Comment by derekpoindexter** [comment]
Hey, thanks for the feedback. I've updated the links. The changes will be live with our next promotion.
