### ISSUE TITLE
Circular Link Detected - OpenShift Changelog/Versions

### ISSUE THREAD

**Issue by ssalerno-ibmcloud** [ibm-cloud-docs/openshift#112]
OpenShift Changelog provides a "see also" to the OpenShift Versions history, but the URL in the link is the same as the current page.

Source: `/openshift_versions_changelog.md`
Doc URL: [Version Change log](https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_changelog)

Incorrect link: _Master patch updates are applied automatically. Worker node patch updates can be applied by reloading or updating the worker nodes. For more information about major, minor, and patch versions and preparation actions between minor versions, see [Red Hat OpenShift versions](https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_changelog)._

Corrected: _Master patch updates are applied automatically. Worker node patch updates can be applied by reloading or updating the worker nodes. For more information about major, minor, and patch versions and preparation actions between minor versions, see [Red Hat OpenShift versions](https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_versions)._

**Comment by derekpoindexter** [comment]
Hey, thanks for the feedback. We're moving some pages around. I redirected these links. The fix should be live soon.

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. We've updated the link.
