### ISSUE TITLE
 OpenShift Data Foundation Essential or Advanced billing plan

### ISSUE THREAD

**Issue by ThomasUllrich666** [ibm-cloud-docs/openshift#113]
Can you please describe the differences between the OpenShift Data Foundation Essential or Advanced billing plan
https://cloud.ibm.com/docs/openshift?topic=openshift-deploy-odf-vpc&interface=ui#odf-vpc-param-ref

I didn't find any documentation regarding this

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've updated the page here. https://cloud.ibm.com/docs/openshift?topic=openshift-ocs-storage-prep&interface=ui#odf-essentials-vs-advanced
