### ISSUE TITLE
Bug: with the migration to Secrets Manager, obtaining the cluster TLS certificate fails

### ISSUE THREAD

**Issue by mekaufman** [ibm-cloud-docs/openshift#114]
Originally opened here: https://github.com/ibm-cloud-docs/account/issues/17 by @ecejjar

Going through https://cloud.ibm.com/docs/openshift?topic=openshift-ingress-roks4#priv-se-priv-controller-2 (step 2):

In IBM Cloud-provided ROKS clusters, Certificate Manager (CM) has been deprecated in favor of Secrets Manager (SM). New clusters are by default provisioned using SM as certificate store.

With SM, the procedure using ibmcloud oc ingress secret create --cert-crn to copy the cluster certificate to the local ingress fails:

Error retrieving secret from the IBM Cloud Secret Manager instance. Try again later. (ECSRCGC) Incident ID: 53e294fe-cd09-460d-899b-fb8950066eb5

The procedure needs to be updated to adapt to the new restrictions imposed by SM.

**Comment by ecejjar** [comment]
Update: the problem stems from how we configured the authorization between the IKS service and the SM service. We did it like this:
![image](https://user-images.githubusercontent.com/7501037/183830403-41c65a6a-0385-4173-be93-137a5221bfc5.png)

, but it has to be done like this instead:
![click-to-athorize](https://user-images.githubusercontent.com/7501037/183830987-e8c20150-757e-4023-866e-9c76c7b890f2.png)

I'll let you decide if you want to mention anything about this in the docs. From our side this bug can be closed.

**Comment by marissa-treible** [comment]
Hi @ecejjar. Thank you for opening this issue. The service authorization steps for Secrets Manager are documented [here](https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-integrations#create-authorization), in the Secrets Manager docs. I'll open an issue with that docs team to see if they want to add any updates based on the info you provided.

**Comment by IdanAdar** [comment]
Marissa, wrong.

the docs clearly state:

Select the required service access role.

Some integrations might require a specific role. To understand which service role is needed, see the documentation for the service that you want to integrate with Secrets Manager.

so, IKS docs should document what IKS needs. It’s not related to SM docs. Thanks.
