### ISSUE TITLE
RHEL migration - Can not scale to 0

### ISSUE THREAD

**Issue by frykshon** [ibm-cloud-docs/openshift#117]
https://cloud.ibm.com/docs/openshift?topic=openshift-cs_versions_411#rhel-migrate-411

In the RHEL 7 --> 8 migration section in step 6 it says to:

`Scale down the worker pool that contains the RHEL 7 hosts by [manually resizing the worker pool to zero](https://cloud.ibm.com/docs/containers?topic=containers-add_workers#resize_pool).`

However you can not scale a pool to 0 - only down to 1. Can step 6 be removed? You only need to remove the pool itself and can not scale to 0 so step 6 is not valid.

**Comment by marissa-treible** [comment]
Hi @frykshon. Thanks for opening this issue. I removed the step and the changes should be published later today.
