### ISSUE TITLE
VPC Control Pane IP's must have access on port 443 (not 80) to avoid ingress warning

### ISSUE THREAD

**Issue by C-nit** [ibm-cloud-docs/openshift#122]
https://cloud.ibm.com/docs/openshift?topic=openshift-ingress-debug-roks4#ping-43
under point 1 in case of VPC, instructions are to ensure ingress access of the control pane IPs has to be allowed for
> either port 80 or 443.

This is not true. To ensure there is no ingress warning the port 443 must be accessible.

Opening/closing port 80 does not affect the ingress warnings, though it may be relevant if one makes a health check via http while debugging.

**Comment by daniel-p-miller** [comment]
Thanks for bringing this to our attention, it will be updated shortly!
