### ISSUE TITLE
Command to check ingress status report

### ISSUE THREAD

**Issue by abhishektuf** [ibm-cloud-docs/openshift#124]
The command mentioned in the pages below has a typo.

Doc URL : https://cloud.ibm.com/docs/openshift?topic=openshift-ingress-status

Command listed:
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/5516977/202070606-8b476149-8959-45d9-8654-11c238aa3a22.png">

Correct command : `ibmcloud oc ingress status-report get -c <cluster_name_or_ID> `

Doc URL : https://cloud.ibm.com/docs/containers?topic=containers-ingress-status

Command listed: 

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/5516977/202070655-08af0cc3-95d1-4726-99ad-27baa0f59bea.png">

Correct command : `ibmcloud ks ingress status-report get -c <cluster_name_or_ID>`

**Comment by derekpoindexter** [comment]
Hey thanks for the feedback. The fix is live now.
