### ISSUE TITLE
Format for link is worng

### ISSUE THREAD

**Issue by JoachimGross** [ibm-cloud-docs/openshift#125]
On the webpage 
[Setting up Ingress](https://cloud.ibm.com/docs/openshift?topic=openshift-ingress-roks4&interface=ui#priv-se-priv-controller) the link in the second Tip is missing a opening [

`For information about how to expose apps in Satellite, see Exposing apps in Satellite clusters](/docs/openshift?topic=openshift-sat-expose-apps).`

It should be 
`For information about how to expose apps in Satellite, see [Exposing apps in Satellite clusters](/docs/openshift?topic=openshift-sat-expose-apps).`

**Comment by derekpoindexter** [comment]
Hey, thanks for the feedback. The fix go live when we promote later today.
