### ISSUE TITLE
wrong command in https://cloud.ibm.com/docs/openshift?topic=openshift-storage-file-vpc-install

### ISSUE THREAD

**Issue by sadoMasupilami** [ibm-cloud-docs/openshift#126]
under Prerequisites the first point:

i think ibmcloud oc plugin update container-service
should be ibmcloud plugin update container-service

the oc in between is probably wrong

**Comment by derekpoindexter** [comment]
Hey, thanks for the feedback. The fix will go live with our promotion later today.
