### ISSUE TITLE
ODF Prerequisites should update the flavour.

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/openshift#129]
The prerequisites section of the ODF doc
https://cloud.ibm.com/docs/openshift?topic=openshift-deploy-odf-vpc&interface=ui#ocs-storage-vpc

states the following:
```
You can deploy OpenShift Data Foundation on 3 worker nodes of 10 CPUs and 32 GB RAM, but you must taint your worker nodes to run only ODF pods. You can't run any additional app workloads or system pods on your ODF nodes when you use this setup.
```

Why 10 vCPUs? ROKS does not have such a flavour. This is either 8 vCPU or 16 vCPU.

**Comment by derekpoindexter** [comment]
Thanks for the feedback. The fix will go live later today.
