### ISSUE TITLE
gx2 profiles missing in VPC flavors link

### ISSUE THREAD

**Issue by orebmann** [ibm-cloud-docs/openshift#131]
No gx2 flavors listed under https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-flavors

Although the release notes from Sep 2022 point to it:
https://cloud.ibm.com/docs/openshift?topic=openshift-openshift-relnotes&interface=ui
"... New! vGPU worker node flavors are now available for VPC Gen 2.
For more information about the available worker node flavors, see [VPC Gen 2 flavors](https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-flavors). Worker node flavors with vGPU support are the gx2 flavor class, for example: gx2.16x128.2v100. ..."

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback.

vGPU worker nodes are behind an allowlist, so they're not included on the flavors page. If you need get to get access to the allowlist you can request it here - https://cloud.ibm.com/docs/openshift?topic=openshift-get-help#allowlist-access-request

Be sure to include the data centers, the VPC infrastructure profile, and the number of workers that you want use. For example `12 worker nodes in us-east-1 of VPC profile gx2-16x128xv100`. For a reference of the VPC instance profiles, you can see - https://cloud.ibm.com/docs/vpc?topic=vpc-profiles&interface=ui#gpu

After you are added to the allowlist, you can see the available flavors in cluster create console or by running `ibmcloud ks flavors`

I've updated the release note you mentioned to refer to the allowlist. The change will go live later today.
