### ISSUE TITLE
error in the yaml

### ISSUE THREAD

**Issue by acamachoArg** [ibm-cloud-docs/openshift#132]
There's an issue in the example yaml from step 3 in https://cloud.ibm.com/docs/openshift?topic=openshift-access_cluster&locale=en#classic_private_se

The variable <private_service_endpoint_port> is missing

It should be like:

apiVersion: v1
kind: Service
metadata:
  name: oc-api-via-nlb
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: private
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: <private_service_endpoint_port>
    targetPort: <private_service_endpoint_port>
---
kind: Endpoints
apiVersion: v1
metadata:
  name: oc-api-via-nlb
  namespace: default
subsets:
  - addresses:
      - ip: 172.20.0.1
    ports:
      - port: 2040

**Comment by daniel-p-miller** [comment]
Thanks for letting us know, this will be fixed with our next prod push.
