### ISSUE TITLE
Command in docs appears to have invalid argument

### ISSUE THREAD

**Issue by mlinnem** [ibm-cloud-docs/openshift#134]
<img width="800" alt="Screenshot 2023-05-24 at 1 29 44 PM" src="https://github.com/ibm-cloud-docs/openshift/assets/1547834/ad137d91-c783-46b7-9f43-7291c8fb98e8">

On the page "https://cloud.ibm.com/docs/openshift?topic=openshift-getting-started&interface=cli" the line "ibmcloud oc cluster create vpc-gen2 --name my_cluster --version 4.11_openshift --zone us-east-1 --vpc-id <VPC_ID> --subnet-id <VPC_SUBNET_ID> --cos-instance <COS_CRN>--flavor b2.4x16 --workers 3" appears to specify a flavor that does not exist, **b2.4x16** . 

I think it is supposed to be a 'bx2.4x16' , the difference being the 'x'.

**Comment by derekpoindexter** [comment]
Hey, thanks for the feedback. The fix will go out with our next promotion later today.

**Comment by mlinnem** [comment]
Thank you!
