### ISSUE TITLE
ODF - Add a section `Setting up encryption by using Key Protect`.

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/openshift#136]
Add a section `Setting up encryption by using Key Protect`.

Today, the doc only mentions `Setting up encryption by using Hyper Protect Crypto Services`

https://cloud.ibm.com/docs/openshift?topic=openshift-deploy-odf-vpc&interface=ui

**Comment by daniel-p-miller** [comment]
Hello @lionelmace , this has been updated in our documentation. Thank you!
