### ISSUE TITLE
Change bringing your own OCP license

### ISSUE THREAD

**Issue by andrewyu-IBM** [ibm-cloud-docs/openshift#138]
At [https://cloud.ibm.com/docs/openshift?topic=openshift-satellite-clusters#byo-ocp-satellite](https://cloud.ibm.com/docs/openshift?topic=openshift-satellite-clusters#byo-ocp-satellite):
However, you can bring your own OpenShift Container Platform license for clusters created with your on-premises infrastructure or for clusters created by using IBM Cloud Paks.

This is not correct. It should be changed to: "However, you can bring your own OpenShift Container Platform license for clusters created with your on-premises infrastructure or for clusters created on-premises by using IBM Cloud Paks."

See Slack thread: https://ibm-cloudplatform.slack.com/archives/C01149RMSCU/p1687344608592929.

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've updated the page and the change will be live with our next promotion later today.
