### ISSUE TITLE
"Important:  You can't use the OpenShift Data Foundation" followed by no more text

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/openshift#139]
https://cloud.ibm.com/docs/openshift?topic=openshift-deploy-odf-classic&interface=ui#odf-cluster-prepare-classic

The shaded IMPORTANT note in this section says just the following:

"Important:  You can't use the OpenShift Data Foundation"

There's clearly meant to be more text there - can't use the Openshift Data Foundation ... on what?  With what?  In what circumstance?  I don't know what's supposed to be there.

**Comment by derekpoindexter** [comment]
Hey, thanks for the feedback. This is an old warning. I've updated the doc to remove it. The change will go live later today
