### ISSUE TITLE
Please add an "Important" note regarding how NOT to update VPC cluster load balancers

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/openshift#143]
In VPC, application & network load balancers that are NOT used with IKS or Openshift clusters can be updated directly, via 'ibmcloud is' commands or in the UI's "VPC Infrastructure" space - for example, to change a frontend listener's port or health check timeout value.

But for VPC load balancers that are tied to IKS/ROKS clusters, as this article indicates, any updates to them should be performed via annotations in the ingress configuration.  That ingress periodically re-syncs with any associated VPC ALBs/NLBs to ensure the running load balancer conforms to the ingress's expected configuration.  So if you make any changes to such a load balancer directly via VPC, instead of using ingress annotations, those changes WILL eventually be reverted back.

**Comment by yingyeliu** [comment]
Hi @john-d-burke , which page shall we add this note to? Thanks.

**Comment by yingyeliu** [comment]
Hi @john-d-burke, which page shall we add this note to? Thanks.

**Comment by john-d-burke** [comment]
My apologies @yingyeliu !  I see I neglected to include that.  It's here:

https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-lbaas#setup_vpc_alb_pub_priv

Just FYI, we've just performed some testing in our test acct on this very subject - we're waiting for a value to get reverted back by the ingress annotation, but we've got screenshots if that would be helpful - if so please feel free to DM me!

**Comment by yingyeliu** [comment]
Thanks, John. The note has been added.

**Comment by john-d-burke** [comment]
@yingyeliu I reviewed the article again, but did not see any new content, and it shows it was last update on July 26.  Is the note going through some sort of approval process?  Thanks!

**Comment by yingyeliu** [comment]
The[ PR](https://github.ibm.com/alchemy-containers/documentation/pull/11722/files) was merged. Sometimes it takes a while for it to show up. I'll post another comment when it shows up on the site. Thanks!

**Comment by yingyeliu** [comment]
The note is showing up now. Thanks.
