### ISSUE TITLE
The end support date needs to be corrected in the Japanese version

### ISSUE THREAD

**Issue by tnakajo** [ibm-cloud-docs/openshift#144]
The end support date needs to be corrected in the Japanese version. (Customer reported via CS3576801)

https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_versions&locale=ja
非推奨: 4.10 (Kubernetes 1.23)
  サポート終了: 2023 年 11 月 1 日

Wrong: サポート終了: 2023 年 11 月 1 日
Expected: サポート終了: 2023 年 11 月 30 日

Reference:
https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_versions&locale=en
Deprecated: 4.10 (Kubernetes 1.23)
End of support: 30 November 2023

**Comment by tnakajo** [comment]
Reference: GHE with IKS (armada) team - https://github.ibm.com/alchemy-containers/customer-tickets/issues/16003#issuecomment-63482880

**Comment by derekpoindexter** [comment]
Thanks for the feedback. I've merged the fix - https://github.ibm.com/cloud-docs/containers/pull/1207/files
