### ISSUE TITLE
Doc should mention that the template use Dedicated Pool

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/openshift#145]
When you try to create a secure cluster by using a template from the UI, it actually uses a dedicated pool
https://cloud.ibm.com/docs/openshift?topic=openshift-templates&interface=ui#sch-secure-cluster-ui

<img width="1064" alt="image" src="https://github.com/ibm-cloud-docs/openshift/assets/12241613/d4288a70-2e2c-437e-870f-08eb0ddd66a4">

Yet, this template requires dedicated pool which is only available to limited users
<img width="825" alt="image" src="https://github.com/ibm-cloud-docs/openshift/assets/12241613/31b628ff-f866-41c9-9aa6-cf14e9a49de0">

**Comment by derekpoindexter** [comment]
This is a console bug -  https://github.ibm.com/alchemy-containers/armada-ui/issues/8604

You can, but don't `have` to use dedicated pools
