### ISSUE TITLE
Correct the instructions to find the Master IP

### ISSUE THREAD

**Issue by ketanvora15** [ibm-cloud-docs/openshift#147]
**Original Document link**: https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-acls#acls_ui

**Document Content**:
Master IPs can be found by looking at the server: entry in the cluster's kubeconfig file (kubectl config view) and then running the nslookup or dig command to determine which IPs that it resolves to. The Master IP can be from 1 to 3 different IPs depending on the region and the control plane cluster.

**Notes**: 
In the given instructions, please clarify, that the user should not add the port number to a DNS query.

**Examples**:
**Wrong query**:
~]# host c100-e.eu-gb.containers.cloud.ibm.com:31773
Host c100-e.eu-gb.containers.cloud.ibm.com:31773 not found: 3(NXDOMAIN)

**Correct query**:
~]# host c100-e.eu-gb.containers.cloud.ibm.com
c100-e.eu-gb.containers.cloud.ibm.com is an alias for c100.eu-gb.containers.cloud.ibm.com.
c100.eu-gb.containers.cloud.ibm.com is an alias for c100.eu-gb.containers.cloudibmcom.zone.akadns.net.
c100.eu-gb.containers.cloudibmcom.zone.akadns.net has address 158.175.125.194

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've updated this page. The changes will be live with our promotion later today
