### ISSUE TITLE
Storage Tier name has been changed

### ISSUE THREAD

**Issue by mkulamarva** [ibm-cloud-docs/openshift#148]
Hi Team

The tier `flex` has been renamed to `smart` - please review the references for `flex` in the documents below-
https://cloud.ibm.com/docs/openshift?topic=openshift-storage_cos_install

**Comment by mkulamarva** [comment]
Also, in IKS documents as well-
https://cloud.ibm.com/docs/containers?topic=containers-storage_cos_install

**Comment by derekpoindexter** [comment]
Thanks for the feedback. I've updated these pages. The changes will be live soon
