### ISSUE TITLE
HyperLink seems to be archived

### ISSUE THREAD

**Issue by mkulamarva** [ibm-cloud-docs/openshift#149]
<img width="762" alt="image" src="https://github.com/ibm-cloud-docs/openshift/assets/104574223/3c456270-0d7b-4982-a2e1-188538e231b3">

Please refer to the below document-
https://cloud.ibm.com/docs/openshift?topic=openshift-storage_cos_install#configure_cos

Under step2 , there is a Tip posted. That blog's hyperlink does not exist and also the flex tier has been renamed to smart tier, so please review this part, thank you.

**Comment by mkulamarva** [comment]
Also in IKS document as well - https://cloud.ibm.com/docs/containers?topic=containers-storage_cos_install#configure_cos

**Comment by derekpoindexter** [comment]
Thanks for the feedback. The link is to an outdated blog. I've removed it. The change will be live soon.
