### ISSUE TITLE
An installation command for ibmcloud does not work

### ISSUE THREAD

**Issue by yamasakk** [ibm-cloud-docs/openshift#150]
Below IBM Cloud Document shows an installation command which does not work for PowerShell:
https://cloud.ibm.com/docs/openshift?topic=openshift-cli-install#cli-install-include-step1-install-idt

PowerShell 7.3.8
PS C:\Users\269399760> iex (New-Object Net.WebClient).DownloadString('https://clis.cloud.ibm.com/install/powershell')
InvalidOperation:
Line |
  36 |  $Arch = (Get-Process -Id $PID).StartInfo.EnvironmentVariables['PROCES …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot index into a null array.

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I will reach out in slack.

**Comment by derekpoindexter** [comment]
Closing here. Track the progress in slack - and GHE https://github.ibm.com/cloud-docs/cli/issues/533
