### ISSUE TITLE
After VRF is enabled - Service Endpoints has to be enabled 

### ISSUE THREAD

**Issue by ranjith-rajaram** [ibm-cloud-docs/openshift#151]
Once the account has been added with VRF user will have to manually enable the Service Endpoints. Steps below,

**Service endpoints**
    Open the Account Settings page - https://cloud.ibm.com/account/settings
    Once "Virtual routing and forwarding" has been enabled, the option to enable "Service endpoints" is available.
    Click the On button to turn service endpoints on.

**Comment by marissa-treible** [comment]
Hi @ranjith-rajaram. Can you link to the doc that this issue is in reference to? Thanks.
