### ISSUE TITLE
OpenShift documentation links back to Kubernetes Service for the section "Planning App Deployments"

### ISSUE THREAD

**Issue by gtstark07** [ibm-cloud-docs/openshift#156]
https://cloud.ibm.com/docs/openshift?topic=openshift-plan_deploy#services_expose_apps

This section of the documentation links back to the Kubernetes service documentation in multiple places. Specifically, it links to the KS version of this document when an OpenShift version exists: https://cloud.ibm.com/docs/openshift?topic=openshift-cs_network_planning

This should be resolved as the user will find themselves in the wrong section of the documentation if they are following subsequent links.

- Standard cluster: You can expose your app by using a [NodePort, load balancer, or Ingress service](https://cloud.ibm.com/docs/containers?topic=containers-cs_network_planning#external).
 
- Cluster that is made private by using Calico: You can expose your app by using a [NodePort, load balancer, or Ingress service](https://cloud.ibm.com/docs/containers?topic=containers-cs_network_planning#private_both_vlans). You also must use a Calico preDNAT network policy to block the public node ports.

- Private VLAN-only standard cluster: You can expose your app by using a [NodePort, load balancer, or Ingress service](https://cloud.ibm.com/docs/containers?topic=containers-cs_network_planning#plan_private_vlan). You also must open the port for the service's private IP address in your firewall.

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback! I've just merged the fix. The updated links will be live soon.
