### ISSUE TITLE
Storage class names showing up as raw HTML elements

### ISSUE THREAD

**Issue by jpapejr** [ibm-cloud-docs/openshift#157]
Source https://cloud.ibm.com/docs/openshift?topic=openshift-storage-file-vpc-sc-ref

![image](https://github.com/ibm-cloud-docs/openshift/assets/213203/3e31e1bf-96e0-457b-85ec-d5f8819ff94f)

**Comment by derekpoindexter** [comment]
Hey, thanks for the feedback. I've just merged the fix. It will be live soon.
