### ISSUE TITLE
Typo for `Vault` storage class type for COS s3fs

### ISSUE THREAD

**Issue by jpapejr** [ibm-cloud-docs/openshift#158]
![image](https://github.com/ibm-cloud-docs/openshift/assets/213203/2c0ea360-bfea-41b0-a343-f13cdd0d4325)

https://cloud.ibm.com/docs/openshift?topic=openshift-storage_cos_reference

**Comment by derekpoindexter** [comment]
Hey, thanks for the feedback. I've just merged the fix. It will be live soon.
