### ISSUE TITLE
Command not present - ROKS

### ISSUE THREAD

**Issue by kmadhushree** [ibm-cloud-docs/openshift#162]
In the below document, in "How to fix it" section,
https://cloud.ibm.com/docs/openshift?topic=openshift-ts-webhook-debug

Under step 1 ie 
Run the following command to get the VPN pod logs. If you can't get the VPN logs, follow the steps to [Debug common CLI issues](https://cloud.ibm.com/docs/openshift?topic=openshift-ts_clis) and return to this page when you are able to retrieve the logs. If the command succeeds and you can get the logs, the VPN tunnel is working and you can continue to the next step.

However no command is provided? I believe to search and get logs of VPN pod, you would need to run,
`oc get pods -n kube-system | grep vpn`
`oc logs <pod-from-above> -n kube-system`

Would you please add that, thank you

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've added the example commands. The change will be live soon.
