### ISSUE TITLE
Command not present - IKS

### ISSUE THREAD

**Issue by kmadhushree** [ibm-cloud-docs/openshift#163]
In the below document, in "How to fix it" section,
https://cloud.ibm.com/docs/containers?topic=containers-ts-webhook-debug

Under step 1 ie
Run the following command to get the VPN pod logs. If you can't get the VPN logs, follow the steps to [Debug common CLI issues](https://cloud.ibm.com/docs/containers?topic=containers-ts_clis) and return to this page when you are able to retrieve the logs. If the command succeeds and you can get the logs, the VPN tunnel is working and you can continue to the next step.

However no command is provided? Also, I believe in IKS there are no VPN pods but the konnectivity-agent? If so, then the commands should be :
kubectl get pods -n kube-system | grep konn
kubectl logs <pod-from-above> -n kube-system

Would you please verify and add that, thank you

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've added the example commands. The change will be live soon.
