### ISSUE TITLE
Doc not uptodate

### ISSUE THREAD

**Issue by vannlam** [ibm-cloud-docs/openshift#164]
Hi,

the documentation is no more to date : 
https://cloud.ibm.com/docs/openshift?topic=openshift-storage-file-vpc-apps#vpc-add-file-static

The command : 
ibmcloud is share-targets SHARE-ID

Does not exist anymore

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've updated the example command. The change will be live soon.
