### ISSUE TITLE
Please update the change log for worker node fix pack 4.13.35

### ISSUE THREAD

**Issue by sivamtkr1102** [ibm-cloud-docs/openshift#165]
There is no changelog for the version 4.13.35 openshift version in IBM Cloud. We have the changelog for 4.13.33 and no details for 4.13.34, 4.13.35 then we have 4.13.36. But in Openshift version we have the 4.13.34 and 4.13.35, please update if we have the logs for versions in IBM Cloud Openshift.
This will help our customers to review about the version changelogs.
https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_changelog_413

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. The 4.13.36 update in IBM Cloud includes the changes from 4.13.35, but because IBM Cloud releases patch updates every 2 weeks you might not see each individual Red Hat release reflected in the IBM Cloud change logs.
