### ISSUE TITLE
link address is 404 

### ISSUE THREAD

**Issue by threen134** [ibm-cloud-docs/openshift#166]
https://cloud.ibm.com/docs/openshift?topic=openshift-overview#compare_ocp

**Comment by threen134** [comment]
![Xnip2024-03-23_22-44-55](https://github.com/ibm-cloud-docs/openshift/assets/13844762/ea0e5226-40e9-45fc-9f09-c3ee1c4ffa9a)

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've update the link. The change will be live soon.
