### ISSUE TITLE
VPC Cluster Load Balancer Settings are controlled via Ingress Annotations and not via UI or ibmcloud is commands

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/openshift#167]
This is documented for VPC Load Balancers used for IKS cluster, and needs to also be documented in the same way in the relevant Openshift documentation for the same configuration:

https://cloud.ibm.com/docs/containers?topic=containers-vpc-lbaas

"IMPORTANT:  VPC ALBs and NLBs that are not tied to Kubernetes or Openshift clusters can be updated directly by using 'ibmcloud is' commands or the VPC Infrastructure section in the console. For example, change a front-end listener's port or health check timeout value. But for VPC load balancers that are tied to Kubernetes or Openshift clusters, any updates to them must be performed via annotations in the Ingress configuration. The Ingress periodically re-syncs with any associated VPC ALBs and NLBs to ensure the running load balancer conforms to the Ingress's expected configuration. So if you make any changes to such a load balancer directly via VPC instead of using Ingress annotations, those changes will be reverted back."

**Comment by marissa-treible** [comment]
Hi @john-d-burke. Thanks for opening this issue. This note is already included in the OpenShift documentation at the bottom of the **Setting up a public or private ALB**  section. 

section https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-lbaas#setup_vpc_alb_pub_priv
