### ISSUE TITLE
Misleading command reference for installing IBM COS plugin

### ISSUE THREAD

**Issue by jbernshine** [ibm-cloud-docs/openshift#168]
On step 10 of the installation instructions for installing the plugin (https://cloud.ibm.com/docs/openshift?topic=openshift-storage_cos_install):

`helm ibmc install ibm-object-storage-plugin ibm-helm/ibm-object-storage-plugin --set license=true [--set quotaLimit=true/false] [--set bucketAccessPolicy=false] [--set allowCrossNsSecret=true/false]`

The default for quotaLimit and allowCrossNsSecret is true, but it is not clearly documented. Setting quotaLimit to true can cause problems with creating PVCs when you don't expect to use quotas. Defaults should be more clear.

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've the updated the page. The change will be live soon.
