### ISSUE TITLE
Correction needed for typo on step 3 of deploying a gpu workload

### ISSUE THREAD

**Issue by frykshon** [ibm-cloud-docs/openshift#171]
Step 3 of (https://cloud.ibm.com/docs/openshift?topic=openshift-deploy_app&interface=ui#gpu-workload) needs to be corrected from "oc get pod -a -l 'name in (nvidia-devicequery)'" to "oc get pod -A -l 'name in (nvidia-devicequery)'"

Thanks in advance!

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've updated the command. The change will be live later today.
