### ISSUE TITLE
cannot find the download link for OpenShift CLI

### ISSUE THREAD

**Issue by Triticum01** [ibm-cloud-docs/openshift#173]
The instruction here: https://cloud.ibm.com/docs/openshift?topic=openshift-cli-install for install OpenShift CLI.  When cli the link it points to the Cluster page. I cannot find the download link there. 

![Screenshot 2024-06-05 at 19 53 46](https://github.com/ibm-cloud-docs/openshift/assets/38061568/98229241-7d27-42c8-8398-06b35bd7cc80)

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. After you create a cluster, you can find the download steps in the **Actions** menu.

<img width="191" alt="Screenshot 2024-06-06 at 9 52 09 AM" src="https://github.com/ibm-cloud-docs/openshift/assets/45565883/70caf3cb-cec8-4447-b092-7cd0f6d9a475">

**Comment by Triticum01** [comment]
The sentence says 'OpenShift CLI'; My understanding it refers to 'oc' cli.  That is what I am looking for-  How to install 'oc' CLI. not how to connect to the cluster.
