### ISSUE TITLE
Openshift Edge Node Ingress - UNSUPPORTED COMMAND in page

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/openshift#174]
https://cloud.ibm.com/docs/openshift?topic=openshift-edge#edge_nodes_alb

Please note that "ibmcloud oc ingress alb ls" is no longer a valid command in ROKS, and has not been for over a year.  Please review with relevant folks for what to replace that with.  Thanks!

**Comment by chaitanyaMantena123** [comment]
Hi @derekpoindexter,

Checking if you got a chance to review the above.

For refer - https://ibm-cloudplatform.slack.com/archives/C54H08JSK/p1719859539872379
https://ibm-cloudplatform.slack.com/archives/CJH0UPN2D/p1719859522783519

Many thanks.

**Comment by derekpoindexter** [comment]
Thanks for the feedback. I'm working with development on the doc updates for this issue. An update will be live soon.

**Comment by derekpoindexter** [comment]
The doc update is live here - https://cloud.ibm.com/docs/openshift?topic=openshift-edge

Thanks for the feedback
