### ISSUE TITLE
'ibmcloud oc ingress alb ls' hasn't been a supported command for at least a year

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/openshift#175]
ibmcloud oc ingress alb ls -c CLUSTERID

Will return: 

"This operation is not supported for your cluster's version. (E3918)"

https://cloud.ibm.com/docs/openshift?topic=openshift-ingress-must-gather

**Comment by mtreible-ibm** [comment]
Hi @john-d-burke

Ingress ALBs are not available for Red Hat OpenShift clusters. I'll check through our docs and make sure that any Ingress ALB references are not available in the Red Hat OpenShift for IBM Cloud documentation. 

For Kubernetes, the `ibmcloud ks ingress alb` commands are supported. These commands replaced the `ibmcloud ks alb` commands, which have been deprecated for over a year.

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. We've updated the Ingress must gather docs for OpenShift - https://cloud.ibm.com/docs/openshift?topic=openshift-ingress-must-gather
