### ISSUE TITLE
Need to add worker node fix pack for 4.14.36 version

### ISSUE THREAD

**Issue by sivamtkr1102** [ibm-cloud-docs/openshift#179]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_changelog_414

### What do you think needs to be updated?

Need the document to be updated with change log for master and worker node fix pack for 4.14.36 openshift version. Please let me know the ETA for the document to be upgraded if any plans to update the doc.

**Comment by kKronstainBrown** [comment]
@sivamtkr1102 The page has been updated. 4.14.37 is the most recent supported fix pack version. Thanks for asking!
