### ISSUE TITLE
Request to add the patch version for worker node 4.16.23_1546_openshift

### ISSUE THREAD

**Issue by sivamtkr1102** [ibm-cloud-docs/openshift#181]
### Which topic are you reporting about?

Please update the change log for worker node patch version 4.16.23_1546_openshift
https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_changelog_416

### What do you think needs to be updated?

https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_changelog_416

**Comment by derekpoindexter** [comment]
Thanks for the feedback. The page has been updated
