### ISSUE TITLE
URL of LogDNA agent yaml file is changed

### ISSUE THREAD

**Issue by ongkhaiwei** [ibm-cloud-docs/openshift#27]
The url from LogDNA git repo is changed from https://raw.githubusercontent.com/logdna/logdna-agent/master/logdna-agent-ds-os.yml to https://raw.githubusercontent.com/logdna/logdna-agent/master/logdna-agent-ds-os.y**a**ml

**Comment by Nadine2016** [comment]
changes are made in staging. thank you for your feedback. the change will go out with our next prod push.
