### ISSUE TITLE
Logdna didn't work with openshift cluster !

### ISSUE THREAD

**Issue by nelemary** [ibm-cloud-docs/openshift#30]
I have followed this article to let LOGDNA logging works with openshift , but it didn't work.
https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_health#openshift_logdna_sysdig_cleanup

**Comment by Nadine2016** [comment]
@nelemary thank you for opening this issue. The LogDNA installation has changed quite a bit, but you can follow this documentation here https://cloud.ibm.com/docs/services/Log-Analysis-with-LogDNA?topic=LogDNA-config_agent_os_cluster to configure it in your cluster. 

We already updated our side of the documentation and will push out the changes with out next prod push. 

Let me know if you have any questions. I am closing this issue for now, but definitely feel free to come back and reopen if you experience any issues.
