### ISSUE TITLE
Broken links 

### ISSUE THREAD

**Issue by ibmchas** [ibm-cloud-docs/openshift#35]
For https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_versions#ocp3to4-migrate-prereqs

It appears that the reference links for IBM Cloud Object Storage in Section 3 are broken, they are all being presented by a **404**

_It got cloudy in here...
Unfortunately, we couldn’t find the page you were looking for, but here are some helpful places to start from:_

**Comment by artberger** [comment]
@ibmchas thank you for raising this issue. I see that these links to sections within the IBM Cloud console do not work. I have removed them, and they will be fixed with the next prod push. I'm going to close this out here.
