### ISSUE TITLE
'oc drain' command incorrect?

### ISSUE THREAD

**Issue by azaceta** [ibm-cloud-docs/openshift#39]
Hi,
I think step 2 for rebooting a node is wrong at: [worker node reboot](https://cloud.ibm.com/docs/openshift?topic=openshift-kubernetes-service-cli#cs_worker_reboot)
as it says to use `oc drain <name>` while it should be `oc add drain <name>`
At least with oc 4.5.

Hope this helps. Regards,
Asier.

**Comment by artberger** [comment]
Thanks @azaceta , I also updated `oc uncordon` to `oc adm uncordon`, and the docs will be updated with the next prod push. I'm going to close this issue, but let us know if you have any other feedback.

Respectfully,
Art
