### ISSUE TITLE
Open container registry route appdomain.cloud to in the firewall section.

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/openshift#43]
In the section [VPC: Opening required ports and IP addresses in other network firewalls](https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-firewall), we should add a section to whitelist the container registry route `*.appdomain.cloud`. I just faced this issue with a client which exposed the openshift container registry externally by following this doc:
https://cloud.ibm.com/docs/openshift?topic=openshift-registry#route_internal_registry

**Comment by lionelmace** [comment]
We also need to at the COS endpoint as the OpenShift registry is stored in COS.
`*.cloud-object-storage.appdomain.cloud`

**Comment by Rachael-Graham** [comment]
Tracking internally at https://github.ibm.com/alchemy-containers/documentation/issues/5727 so closing this issue in favor of the internal one
