### ISSUE TITLE
Prohibited term: master

### ISSUE THREAD

**Issue by cdmauney** [ibm-cloud-docs/openshift#44]
Do not use. Use another term such as "controller," "leader," "parent," or "primary."

https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_changelog

**Comment by artberger** [comment]
Hi @cdmauney , we are tracking this issue across a couple of our services [in this internal issue](https://github.ibm.com/alchemy-containers/documentation/issues/5756). Do you mind if I close this out here and continue working on that one? If so, just reopen this!
