### ISSUE TITLE
Need an update on how to enable vlan spanning - https://cloud.ibm.com/docs/openshift?topic=openshift-subnets#basics_segmentation

### ISSUE THREAD

**Issue by meiaus** [ibm-cloud-docs/openshift#45]
I think the link is missing an important step to actually enable the vlan spanning: https://cloud.ibm.com/docs/openshift?topic=openshift-subnets#basics_segmentation.  This link only describes the first step to grant the permission for vlan spanning from Manage -> Access (IAM) -> Users -> person name -> Classic infrastructure tab and select/check the box of Network > Manage Network VLAN Spanning,  but after the permission granted, 2nd step needs to 'enable' it through Classic Infrastructure (from hamburger menu) -> IP Management -> VLANs, on the vlans page, expand :

![image](https://user-images.githubusercontent.com/27024803/86980399-56b99e00-c149-11ea-847c-69d27205282a.png)

![image](https://user-images.githubusercontent.com/27024803/86980254-ff1b3280-c148-11ea-811a-96a7ee716a1f.png)

It's shown ad Disabled by default. Then click on Enabled text,

![image](https://user-images.githubusercontent.com/27024803/86980285-13f7c600-c149-11ea-9e6d-c88f801bd60a.png)

Checking from CLI: 

# ibmcloud oc vlan spanning get --region us-south
OK
VLAN spanning is enabled.

**Comment by meiaus** [comment]
It's noted the enabling vlan spanning steps are already documented in https://cloud.ibm.com/docs/vlans?topic=vlans-vlan-spanning but it's currently shown as a link in https://cloud.ibm.com/docs/openshift?topic=openshift-subnets#basics_segmentation as follows, which is not clearly directed from "basics_segmentation" page:

![image](https://user-images.githubusercontent.com/27024803/87258729-7fa0a280-c46b-11ea-8193-b77776b48cbb.png)

**Comment by artberger** [comment]
@meiaus thank you for raising this issue. I changed the doc to use the link in the description instead of the title. This change will go out in the next doc prod push, and will look like:
> **VLAN spanning**
> If you cannot or do not want to enable VRF, [enable VLAN spanning](https://cloud.ibm.com/docs/vlans?topic=vlans-vlan-spanning). To perform this action, you need the...

I'm going to close this issue, but let us know if you have other feedback. Thanks again.

**Comment by meiaus** [comment]
Thanks @artberger for the update.
