### ISSUE TITLE
about network of Openshift native with calico and CNI. 

### ISSUE THREAD

**Issue by doyoungim999** [ibm-cloud-docs/openshift#46]
On https://cloud.ibm.com/docs/openshift?topic=openshift-cs_ov#compare_ocp

Can you refer the following link about network ? 
https://docs.openshift.com/container-platform/4.5/networking/openshift_sdn/about-openshift-sdn.html

I am confused a little bit about network part. 
In my understanding,  default network is using OVS. 
"This Pod network is established and maintained by the OpenShift SDN, which configures an overlay network using Open vSwitch (OVS)." ( https://docs.openshift.com/container-platform/4.5/networking/openshift_sdn/about-openshift-sdn.html)

**Comment by artberger** [comment]
@doyoungim999 thank you for raising this issue. I removed the part about being calico by default in OCP, and this change will go out with the next docs prod push. I am going to close this for now, but let us know if you have any other feedback. Thanks again!
