### ISSUE TITLE
Copy to clipboard icon missing

### ISSUE THREAD

**Issue by xiepingp** [ibm-cloud-docs/openshift#47]
Commands should have a "copy to clipboard" icon next to them. Below pages have very many commands without the Copy to clipboard icon which is inconvenient for people who wants to copy these commands:
https://cloud.ibm.com/docs/openshift?topic=openshift-users
https://cloud.ibm.com/docs/openshift?topic=openshift-add_workers
https://cloud.ibm.com/docs/openshift?topic=openshift-network_policies
https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_apps
https://cloud.ibm.com/docs/openshift?topic=openshift-ingress-settings
https://cloud.ibm.com/docs/openshift?topic=openshift-block_storage
https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-block
https://cloud.ibm.com/docs/openshift?topic=openshift-kubernetes-service-cli
https://cloud.ibm.com/docs/openshift?topic=openshift-cs_troubleshoot
https://cloud.ibm.com/docs/openshift?topic=openshift-cs_troubleshoot_clusters

Screenshots please refer to below:
![K5 no Copy button 09](https://user-images.githubusercontent.com/63960906/88362853-9e2e6400-cdb0-11ea-8c9f-5bd66822fad8.png)
![K5 no Copy button 10](https://user-images.githubusercontent.com/63960906/88362860-a1295480-cdb0-11ea-93f4-66eecffd6aea.png)
![K5 no Copy button 11](https://user-images.githubusercontent.com/63960906/88362861-a2f31800-cdb0-11ea-8554-91e192d0aa53.png)
![K5 no Copy button 12](https://user-images.githubusercontent.com/63960906/88362863-a4244500-cdb0-11ea-8c2f-9a574f060ba8.png)
![K5 no Copy button 13](https://user-images.githubusercontent.com/63960906/88362868-a5557200-cdb0-11ea-8301-947c21039f56.png)
![K5 no Copy button 14](https://user-images.githubusercontent.com/63960906/88362869-a5ee0880-cdb0-11ea-9a56-732b36d4fea2.png)
![K5 no Copy button 15](https://user-images.githubusercontent.com/63960906/88362871-a6869f00-cdb0-11ea-9551-87ca3fb42148.png)
![K5 no Copy button 16](https://user-images.githubusercontent.com/63960906/88362875-a7b7cc00-cdb0-11ea-922c-63898fa1f1a2.png)
![K5 no Copy button 17](https://user-images.githubusercontent.com/63960906/88362878-a8506280-cdb0-11ea-8089-908e489985a4.png)

**Comment by artberger** [comment]
Thank you @xiepingp , I updated the docs in our source code, and these should be updated in the next doc prod push. I will close this issue.

**Comment by xiepingp** [comment]
@artberger Thanks for the fixing!!
