### ISSUE TITLE
<GSSC>Invalid menu link under Tutorials

### ISSUE THREAD

**Issue by xiepingp** [ibm-cloud-docs/openshift#49]
For https://cloud.ibm.com/docs/docs?topic=solution-tutorials?topic=solution-tutorials-scalable-webapp-openshift
The reference link for Scalable web application on OpenShift in Tutorials is broken:
![Screen Shot 2020-09-08 at 6 22 24 PM](https://user-images.githubusercontent.com/63960906/92464805-43d25100-f200-11ea-86aa-c6cd1387838a.png)

**Comment by artberger** [comment]
Thank you, I have updated this in the source file and it should be fixed with the next prod push.

**Comment by xiepingp** [comment]
I can see the page now, thanks for the fixing!
![49 fixed](https://user-images.githubusercontent.com/63960906/100829029-6391b200-349b-11eb-8f51-4f539ce361cc.png)
