### ISSUE TITLE
Requirement to use ubuntu stated in the doc,when this clearly isn't the case post openshift aquisition

### ISSUE THREAD

**Issue by robbytherobotibm** [ibm-cloud-docs/openshift#50]
see below for the text on the webpage.    Surely the requirement is to use Redhat UBI, or even - if it's going to really be agnostic - any type of Linux with a certain kernel type?  Whatever the answer - it's probably not uniquely Ubuntu.

"What kind of apps can I run? Can I move existing apps, or do I need to develop new apps?
Your containerized app must be able to run on the supported operating system, **Ubuntu 16.64, 18.64**. You also want to consider the statefulness of your app. For more information about the kinds of apps that can run in Red Hat OpenShift on IBM Cloud, see Planning app deployments."

**Comment by artberger** [comment]
@robbytherobotibm thank you for raising this issue. Yes, we had the wrong conref in place; it should be fixed in the next prod push. The Ubuntu requirement is if your clusters run the Kubernetes platform. For the OpenShift platform, it must be compatible with the underlying RHEL 7.
