### ISSUE TITLE
Openshift VPC tutorial uses wrong command making it fail

### ISSUE THREAD

**Issue by jmkanz** [ibm-cloud-docs/openshift#52]
In the following tutorial for OpenShift of VPC there is an incorrect command listed which causes the tutorial to not work:

https://cloud.ibm.com/docs/openshift?topic=openshift-vpc_rh_tutorial

The command in question is in Step 3: Setting up a VPC load balancer to expose your app publicly

The first command given is to run this: 

`$ oc expose deployment/hello-world --type=LoadBalancer --name=hw-lb-svc  --port=8080 --target-port=8080`

Running the above command will result in an error that no deployment exists with the name "hello-world" and this is correct.

Since we created the application in the cluster using Openshift command:
`$ oc new-app --name hello-world https://github.com/IBM/container-service-getting-started-wt --context-dir="Lab 1"`

This creates a deployment config as opposed to the Kubernetes default deployment. Therefore, the correct command that customers will need to run is:

`$ oc expose dc/hello-world --type=LoadBalancer --name=hw-lb-svc  --port=8080 --target-port=8080`

This command will properly expose the application and created the LoadBalancer service. I suspect this was do the the tutorial initially being created for Kubernetes and not for OpenShift.

**Comment by Rachael-Graham** [comment]
Ah, great catch @jmkanz yes you're right - we started this tutorial originally in Kube! Making the doc changes, which will go out today. Re-open if you have any further questions or suggestions
