### ISSUE TITLE
Incorrect URL definition: Reviewing volume attachment details for a VPC worker node

### ISSUE THREAD

**Issue by dwakeman** [ibm-cloud-docs/openshift#54]
I have been following the docs to manually add VPC block storage to my worker nodes in preparation for installing Portworx.  On this page in step 4 of the section for [reviewing volume attachment details for a VPC worker node](https://cloud.ibm.com/docs/openshift?topic=openshift-utilities#vpc_api_get_worker) the URL in the cURL command is incorrect.

This is what is in the Docs:
curl -X GET -H "Authorization: <IAM_token>" -H "Content-Type: application/json" -H "X-Auth-Resource-Group-ID: <resource_group_ID>" "https://<region>.containers.cloud.ibm.com/v2/storage/clusters/<cluster_ID>/workers/<worker_ID>/volume_attachments"

The result of this command is a `404 page not found`. 

After reviewing the actual API docs I found the docs for the API for [reviewing attached volumes](https://cloud.ibm.com/apidocs/kubernetes#getattachmentslist).  The relatative URL should be `/v2/storage/vpc/getAttachmentsList`.

the command in step 4 looks like it should be:

curl -X GET -H "Authorization: <IAM_token>" -H "Content-Type: application/json" -H "X-Auth-Resource-Group-ID: <resource_group_ID>" "https://<region>.containers.cloud.ibm.com/v2/storage/vpc/getAttachmentList?cluster=<cluster_ID>&worker=<worker_ID>"

I tested the URL using that format and it does work.

Thanks!

**Comment by Rachael-Graham** [comment]
Updated the docs! Thank you.
