### ISSUE TITLE
Route annotation documentation 

### ISSUE THREAD

**Issue by ykoyfman** [ibm-cloud-docs/openshift#55]
This page: https://cloud.ibm.com/docs/openshift?topic=openshift-ingress_annotation has these instructions for annotating routes -

```To add annotations to the router, run oc edit svc router-default -n openshift-ingress.```

In my 4.3 Cluster, it appears I have to edit the route object itself (e.g. oc edit route <name>) .. not the service .. to enable annotations. Adding them to the service has no effect.

**Comment by Rachael-Graham** [comment]
Hm, I think the doc is wrong here. I spoke with the Ingress development team, and they said that you'd need to edit the _router_ not the router service (as is currently in the docs). So I can make that change. But you said that you edited the _route_ itself, not the router - this is work for you? did the annotations actually get applied to the route?

**Comment by Rachael-Graham** [comment]
Fixed!
