### ISSUE TITLE
Wrong subnet addresses in openshift_firewall.md

### ISSUE THREAD

**Issue by pawel-st** [ibm-cloud-docs/openshift#56]
Hi, the following subnet addresses are incorrect with mask "/29" :
161.202.146.86/29, 128.168.71.70/29, 165.192.71.222/29 in "AP North" table row in "IBM Cloud Container Registry" section of openshift_firewall.md
Would you be able to fix it ?
Also have you considered publishing the IP addresses as a simple text list - like here, for example : https://www.cloudflare.com/ips-v4 (https://www.cloudflare.com/ips/) or something like this : https://api.cis.cloud.ibm.com/v1/ips.  It would be very helpful when the proper firewall rules need to be updated due to IP address change.
Thanks

**Comment by Rachael-Graham** [comment]
Thank you, this is fixed now.
I also opened another internal issue to track automation of publishing IPs in a text page separately from the docs.
Thank you!
