### ISSUE TITLE
Service limitations - Multifactor authentication

### ISSUE THREAD

**Issue by ramonvanstijn** [ibm-cloud-docs/openshift#57]
On https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_limitations it is stated that If your account uses multifactor authentication (MFA), the OpenShift web console cannot authenticate and does not work.

My account uses MFA and the OpenShift web console works. I have tested with both OCP version 4.4 and 4.5.

Please validate this is no longer a limitation and remove the limitation from the documentation if applicable.

**Comment by artberger** [comment]
Thank you for raising this issue. I have removed the limitation from our source doc, and the changes will be updated in our next prod push. I'm going to close this here, but let us know if you have any other feedback. Thanks!
