### ISSUE TITLE
Cannot find passport advantage account id that matches format 1aa111aa1a11111aaa1a1111aa1aa111

### ISSUE THREAD

**Issue by xzlin** [ibm-cloud-docs/openshift#58]
In this section https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_cloud_paks#oc_cloud_paks_assign, step 1b, I can not find account id in passport advantage that has the same format as in step 1a.

**Comment by artberger** [comment]
@xzlin sorry to hear that. A couple questions:

* Did your IBM Cloud account ID match that format?
* Could you try the next step and see if they can help you?

> Compare the IDs. If the IDs do not match, try using a different IBM Cloud or IBM Passport Advantage account that match. If you cannot find matching IDs, contact eCustomer care: https://www-112.ibm.com/software/howtobuy/passportadvantage/homepage/ecarec.

**Comment by xzlin** [comment]
@artberger I have access to a few IBM passport advantage accounts. None of them has id like what I listed in the title. I checked with eCustomer care. They confirmed that passport advantage accounts don't have any id like that.

**Comment by artberger** [comment]
@xzlin can you give them the IBM Cloud account ID that you want to use your entitlement with and ask them to assign the entitlement to that IBM Cloud account?

**Comment by artberger** [comment]
The docs were updated for this. Thanks for raising the issue.
