### ISSUE TITLE
Document is unclear leading to implementation errors

### ISSUE THREAD

**Issue by rtpurificacao** [ibm-cloud-docs/openshift#61]
When following the official document [1] to set up object store to be used by apps deployed in Openshift we got some issues that in some way is because the document is not very clear describing some of the steps.

For example in this document is not very clear that for openshift 4.X you need to use Helm version 3.

More in the section "Adding object storage to apps" [2] ,some of the options in the configuration file we can delete or comment them because they are not need it. ( of course depends of the configuration of the COS, but this should be referred in the document).

[1]https://cloud.ibm.com/docs/openshift?topic=openshift-object_storage
[2] https://cloud.ibm.com/docs/openshift?topic=openshift-object_storage#add_cos

**Comment by derekpoindexter** [comment]
@rtpurificacao Thanks for the feedback. I'm working on updates to the documentation. For [2] - Which configuration options are you referring to?
