### ISSUE TITLE
User access permissions has a link that is not formatted correctly

### ISSUE THREAD

**Issue by aerwin** [ibm-cloud-docs/openshift#62]
The [User access permissions](https://cloud.ibm.com/docs/openshift?topic=openshift-access_reference) page has a link that is not formatted correctly:

![image](https://user-images.githubusercontent.com/1258743/112785838-90557080-901a-11eb-9a45-fe9da5ba51eb.png)

**Comment by Rachael-Graham** [comment]
Yep, that was formatted incorrectly. Updated in upstream docs and will be promoted to production soon. Thank you!
