### ISSUE TITLE
Minor typos in topic=openshift-health-monitor

### ISSUE THREAD

**Issue by matrober-uk** [ibm-cloud-docs/openshift#63]
Hi folks,

I spotted some minor typos in the https://cloud.ibm.com/docs/openshift?topic=openshift-health-monitor page - looks like some letters could have been missed during a copy/paste.

- "Built-in OpenShift monitoring tools" section;
  - "clumetrics"
  - "caaccessed"
  - "persisstorage"
- "Forwarding cluster and app metrics to IBM Cloud Monitoring" section
  - "you can collects cluster and pod metrics" (should be "collect")
- "Master states"
  - "Your Red Hat OpenShift on IBM Cloud includes an IBM-managed" - should this have the word "cluster" after "IBM Cloud"?

Regards,

Matt

**Comment by Rachael-Graham** [comment]
Yep, looks like some words were muddled in a copy+paste, and thank you for catching those! Appreciate it. Updated upstream and promoting to production soon.
