### ISSUE TITLE
virtual server link missing

### ISSUE THREAD

**Issue by SionArtingstall** [ibm-cloud-docs/openshift#64]
Virtual Server Link not working in sentence `In VPC clusters, make sure to select a [virtual server](https://cloud.ibm.com/docs/vpc-on-classic-vsi?topic=vpc-on-classic-vsi-profiles) flavor that meets the minimum hardware requirements for Portworx.`

Cannot find this link but have found one for VPC https://cloud.ibm.com/docs/vpc?topic=vpc-profiles.

**Comment by Rachael-Graham** [comment]
Thanks! This is broken because it was still pointing to the deprecated VPC Gen 1 docs instead of the Gen 2 docs. I did a sweep to catch a few other of these old links too. Updated upstream and will promote fixes to prod soon.
