### ISSUE TITLE
Minor typo on Monitoring page

### ISSUE THREAD

**Issue by matrober-uk** [ibm-cloud-docs/openshift#65]
At step 3 in https://cloud.ibm.com/docs/openshift?topic=openshift-health-monitor#openshift_monitoring;
```
oc get daemon sets -n ibm-observe
```
gives an error if you try to execute it in the CLI, and should be as follows (removing extra space in between the words)
```
oc get daemonsets -n ibm-observe
```

**Comment by Rachael-Graham** [comment]
Thank you, updating upstream and will make it to production soon!
