### ISSUE TITLE
Min 9 worker nodes for HA

### ISSUE THREAD

**Issue by BartBogaert** [ibm-cloud-docs/openshift#66]
According to the documentation for a HA the setup is : "with a total of at least 9 worker nodes, three worker nodes per zone that are evenly spread across three zones."

Sorry, this is not acceptable, in case your workload can be run on 1 worker node there is no reason to have at least 3 per zone

More correct would be that the sum of 2 zones out of 3 must be able to run the entire workload, so in case 1 zone goes down the workload remains available at expected performance.

**Comment by derekpoindexter** [comment]
Hi, thank you for the feedback. The HA requirement that is specified in the docs is the most highly available, cost-efficient set up to receive full HA coverage under the SLA terms. This set up might exceed the minimum HA requirements for some workloads, but the level of availability that you set up for your cluster impacts your coverage under the IBM Cloud HA service level agreement terms. You can review the SLA terms here: https://cloud.ibm.com/docs/overview?topic=overview-slas
