### ISSUE TITLE
NAME is required for creating a standard object storage instance

### ISSUE THREAD

**Issue by hidekazuna** [ibm-cloud-docs/openshift#67]
To create a VPC cluster from the CLI, `--cos-instance <cos_CRN>` parameter is required.
To create a standard object storage instance,  command is guided as follows, but NAME is not given so failed to create.
`ibmcloud resource service-instance-create  cloud-object-storage standard global`

I run the following and created a standard object storage instance successfully.
`ibmcloud resource service-instance-create my-object-storage cloud-object-storage standard global`

Document URL:
https://cloud.ibm.com/docs/openshift?topic=openshift-clusters&locale=en#cluster_vpcg2_cli

**Comment by artberger** [comment]
@hidekazuna thank you for raising this issue. I checked, and our formatting for the service name was incorrect as you mentioned. I fixed this in our source code, and the doc change should go out with our next prod push. I'm going to close this issue here. Thanks again!
