### ISSUE TITLE
deployed state can not seen in the output of ibmcloud oc cluster ls command

### ISSUE THREAD

**Issue by hidekazuna** [ibm-cloud-docs/openshift#69]
Document says "When the provisioning of your OpenShift master is completed, the status of your cluster changes to deployed." and the output of `ibmcloud oc cluster ls` is shown.

But we can not see `deployed` state by `ibmcloud oc cluster ls` actually. we can see the state by `ibmcloud oc cluster get --cluster mycluster`.

Worker state is the same.

URL: https://cloud.ibm.com/docs/openshift?topic=openshift-clusters&locale=en#cluster_vpcg2_cli

**Comment by artberger** [comment]
@hidekazuna thanks for raising this issue. You are right, the state name is actually `normal`, not `deployed` anymore. I updated the doc, and the change will go out with the next prod push. Going to close this here.
