### ISSUE TITLE
Link to OpenShift Data Foundation add-on is broken

### ISSUE THREAD

**Issue by arthurbarr** [ibm-cloud-docs/openshift#70]
The [add-on page](https://cloud.ibm.com/docs/openshift?topic=openshift-managed-addons) links to the [OpenShift Data Foundation](https://cloud.ibm.com/docs/openshift?topic=openshift-ocs-storage-prep), page, which does not exist.

**Comment by Rachael-Graham** [comment]
Thank you - This should link to [this page](https://cloud.ibm.com/docs/openshift?topic=openshift-deploy-odf-vpc) instead. The code has been updated upstream and will be pushed to production shortly. Thank you!
