### ISSUE TITLE
Add "for Classic clusters" to the topic "Network segmentation and privacy"

### ISSUE THREAD

**Issue by jxadro** [ibm-cloud-docs/openshift#72]
Hi,

The tittle for this link https://cloud.ibm.com/docs/openshift?topic=openshift-security#network_segmentation is "Network segmentation and privacy"

If you continue reading then you will see the title "Network segmentation and privacy **for VPC clusters**" (https://cloud.ibm.com/docs/openshift?topic=openshift-security#network_segmentation_vpc)

In my case I have a cluster in VPC and I wasted some hours try to understand how to apply the things explained in the first section until I realized it only applies to Classic seeing that there is a specific topic for "VPC clusters".

So I think, in case the first section only applies to classic, that "for Classic clusters" should be added to the tittle.

Thank you.

**Comment by kersten1** [comment]
Hello
Sorry about that. I will open an issue to get that fixed ASAP.

Thanks!
