### ISSUE TITLE
Time to setup by adding required commands to retrieve public IPs

### ISSUE THREAD

**Issue by dusijcloud** [ibm-cloud-docs/openshift#74]
It will be productive if you include the command to retrieve public IP of hosts tahn trying to research in the interest of time.
In this step where command needs to be included
2. Retrieve the matching public IP addresses of your hosts from your cloud provider. at this link https://cloud.ibm.com/docs/openshift?topic=openshift-access_cluster#sat_public_access

**Comment by mltreible** [comment]
Hi @dusijcloud. Thanks for opening this issue. I added the `ibmcloud sat host ls --location` command in the step to retrieve the host IP address.

**Comment by marissa-treible** [comment]
Hi @dusijcloud. Thanks for opening this issue. I've added the `ibmcloud sat host ls --location` command in the step to retrieve the host IP address.
