### ISSUE TITLE
Wrong Permissions Listed

### ISSUE THREAD

**Issue by Callum-Hubka** [ibm-cloud-docs/openshift#75]
Under "Permissions to create a cluster" it says you might need to edit "Identity and Access Management" to include "Service ID creator" and "User API key creator". These are really under "IAM Identity Service".
https://cloud.ibm.com/docs/openshift?topic=openshift-access_reference#cluster_create_permissions

**Comment by derekpoindexter** [comment]
Thanks for the feedback. I've udpated the doc.
