### ISSUE TITLE
Code blocks not indented correctly - caused customer issue

### ISSUE THREAD

**Issue by tim-minter** [ibm-cloud-docs/openshift#76]
https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-lbaas#setup_vpc_nlb_pub
Hi, Essentially code blocks on this page, if used "as is" will result in silent failure if applied to Openshift. The behaviour the instructions are talking about will not happen and in fact the user won't get an error.

In the three code blocks containing this kind of yaml...

`apiVersion: v1
 kind: Service
 metadata:
     name: <app_name>-vpc-nlb-<VPC_zone>
 annotations:
   service.kubernetes.io/ibm-load-balancer-cloud-provider-enable-features: "nlb"
   service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: "public"
   service.kubernetes.io/ibm-load-balancer-cloud-provider-vpc-node-selector: "<key>=<value>"
   service.kubernetes.io/ibm-load-balancer-cloud-provider-vpc-subnets: "<subnet1_ID,subnet2_ID>"
   service.kubernetes.io/ibm-load-balancer-cloud-provider-zone: "<zone>"
spec:
 type: LoadBalancer
 selector:
   <selector_key>: <selector_value>
 ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
 externalTrafficPolicy: Local`

The annotations section needs to be a subsection of the metadata tag. As it is the annotations section will be ignored meaning the yaml will be applied but the NLB will not be created (any of the other annotation's functions will also not take effect).

Recreated using Safari and Chrome on MacOS

**Comment by kersten1** [comment]
Should be fixed now. Please reopen if that is not the case.
