### ISSUE TITLE
Formatting under the Release History section is broken

### ISSUE THREAD

**Issue by gtstark07** [ibm-cloud-docs/openshift#78]
https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_versions#openshift_release_history

Looks like below: 

 Supported? | OpenShift | Kubernetes version | Red Hat OpenShift on IBM Cloud release date | Red Hat OpenShift on IBM Cloud unsupported date | | --- | --- | --- | --- | | Supported | 4.7 / 1.20 | 09 Jun 2021 | Jun 2022† | | Supported | 4.6 / 1.19 | 17 Feb 2021 | Apr 2022 † | | Supported | 4.5 / 1.18 | 13 Oct 2020 | 30 Sep 2021 † | | Not supported | 4.4 / 1.17 | 21 Jul 2020 | 31 May 2021 | | Not supported | 4.3 / 1.16 | 20 Apr 2020 | 7 Mar 2021 | | Deprecated | 3.11 / 1.11 | 01 Aug 2019 | 06 Jun 2022 † |

I am assuming this is supposed to be in tabular form.

**Comment by derekpoindexter** [comment]
Thanks for the feedback! I've updated the table.
