### ISSUE TITLE
Deploying OpenShift Data Foundation on VPC clusters

### ISSUE THREAD

**Issue by ramonvanstijn** [ibm-cloud-docs/openshift#79]
Step 1) on https://cloud.ibm.com/docs/openshift?topic=openshift-deploy-odf-vpc#ocs-storage-vpc states to install the oc CLI.

Users that have it already installed but not the latest version of plugin `container-service[kubernetes-service]` will be unable to enable the ODF addon and see the message:
```
FAILED
'openshift-data-foundation' is not a registered command. See 'ibmcloud ks cluster addon enable help'.
```
These users need to update the plugin.

My request is to make Step 1) one look like:
1.  [Install the oc CLI](https://cloud.ibm.com/docs/openshift?topic=openshift-openshift-cli#cli_oc) or [update the oc CLI](https://cloud.ibm.com/docs/openshift?topic=openshift-openshift-cli#cs_cli_upgrade)

**Comment by derekpoindexter** [comment]
Thanks for the feedback. I've updated the docs to include the update step if you already have the CLI installed.
