### ISSUE TITLE
typo in https://cloud.ibm.com/docs/openshift?topic=openshift-ocs-storage-prep

### ISSUE THREAD

**Issue by kramvan1** [ibm-cloud-docs/openshift#81]
Under `How does OpenShift Data Foundation work?`

`Because ODF abstracts your underlying storage, you can create use ODF to creat File, Block, or Object storage claims all from the same underlying raw block storage.`

`you can create use ODF to creat File,` should probably be `you can use ODF to create File,`

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've corrected the typo.
