### ISSUE TITLE
Link in Debugging Ingress does not resolve

### ISSUE THREAD

**Issue by jxrudy** [ibm-cloud-docs/openshift#86]
[Debugging Ingress](https://cloud.ibm.com/docs/openshift?topic=openshift-ingress-debug-roks4)  has For more information, see the [announcement](https://cloud.ibm.com/notifications?selected=1621697674798), whih does not resolve correctly.

**Comment by derekpoindexter** [comment]
Hi, thank you for the feedback. I've updated this page with the information from the announcement.
