### ISSUE TITLE
Apparent broken markdown table in the noted topic URL

### ISSUE THREAD

**Issue by jpapejr** [ibm-cloud-docs/openshift#87]
Topic:
https://cloud.ibm.com/docs/openshift?topic=openshift-cs_network_planning#routes-vs-ingress

<img width="1012" alt="Screen Shot 2021-10-14 at 3 49 59 PM" src="https://user-images.githubusercontent.com/213203/137385926-00a56e67-5abc-430d-b7fe-0886b34c8c8a.png">

**Comment by derekpoindexter** [comment]
Thanks for the feedback. I've updated this page.
