### ISSUE TITLE
Update ODF page with Billing information

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/openshift#91]
Doc mentions that billing starts on Oct 15, 2021. We're now Nov 23. We should update this page with billing information.

https://cloud.ibm.com/docs/openshift?topic=openshift-deploy-odf-vpc

```
Billing for OpenShift Data Foundation begins 15 October 2021. If you want to try the add-on, but avoid incurring costs, make sure to disable the add-on before 15 October 2021.
```

**Comment by derekpoindexter** [comment]
Hi, thanks for the feeback. In general we don't cover billing details in the docs, we rely on the UI and product pricing pages. Currently the UI team is working on a custom UI for ODF which will include billing details. I've linked this issue to our internal issue for tracking this work.
