### ISSUE TITLE
create satellite options incorrect in docs

### ISSUE THREAD

**Issue by frykshon** [ibm-cloud-docs/openshift#93]
In the Satellite commands section of the docs it refers to "--enable-admin-agent" however the cli no longer has that option, the cli now shows "--enable-config-admin" instead.

https://cloud.ibm.com/docs/openshift?topic=openshift-kubernetes-service-cli#sat_commands

Would like to get this specific wording updated:

From:
>"ibmcloud oc cluster create satellite --location LOCATION --name NAME --pull-secret SECRET --version VERSION [--enable-admin-agent] [--host-label LABEL ...] [--pod-subnet SUBNET] [-q] [--service-subnet SUBNET] [--workers COUNT] [--zone ZONE]"

To:
>"ibmcloud oc cluster create satellite --location LOCATION --name NAME --version VERSION [--enable-config-admin] [--host-label LABEL ...] [--pod-subnet SUBNET] [--pull-secret SECRET] [-q] [--service-subnet SUBNET] [--workers COUNT] [--zone ZONE]"

You can verify the new verbiage in the cli with "ibmcloud oc cluster create satellite --help".

**Comment by derekpoindexter** [comment]
Hi, thank you for the feedback. I've updated the examples and the changes will go live with our next promotion.

**Comment by derekpoindexter** [comment]
The updates are live.
