### ISSUE TITLE
zone add satellite options incorrect 

### ISSUE THREAD

**Issue by frykshon** [ibm-cloud-docs/openshift#94]
In the 'ibmcloud oc zone add satellite' it refers to classic instead of satellite. Can this be changed to refer to satellite instead?

https://cloud.ibm.com/docs/openshift?topic=openshift-kubernetes-service-cli#cs_zone_add_sat

From:
>ibmcloud oc zone add classic --zone ZONE --cluster CLUSTER --worker-pool WORKER_POOL [--output json] [-q]

To:
>ibmcloud oc zone add satellite --cluster CLUSTER --zone ZONE [--output OUTPUT] [-p POOL ...] [-q]

**Comment by derekpoindexter** [comment]
Hi, thank you for the feedback. I've updated the examples and the changes will go live with our next promotion.

**Comment by derekpoindexter** [comment]
The updates are live.
