### ISSUE TITLE
Example zone add satellite has no -w option, looks like it should be -p

### ISSUE THREAD

**Issue by frykshon** [ibm-cloud-docs/openshift#95]
In the zone add satellite section the example shows a -w option but that doesn't appear to be an option in the CLI.

https://cloud.ibm.com/docs/openshift?topic=openshift-kubernetes-service-cli#cs_zone_add_sat

The example currently says:

>ibmcloud oc zone add satellite --zone myzone2 --cluster my_cluster -w pool1 -w pool2

This should be:

>ibmcloud oc zone add satellite --zone myzone2 --cluster my_cluster -p pool1 -p pool2

**Comment by derekpoindexter** [comment]
Hi, thank you for the feedback. I've updated the examples and the changes will go live with our next promotion.

**Comment by derekpoindexter** [comment]
The updates are live.
