### ISSUE TITLE
Typographical Error - OpenSSL Instructions

### ISSUE THREAD

**Issue by ssalerno-ibmcloud** [ibm-cloud-docs/openshift#96]
https://cloud.ibm.com/docs/openshift?topic=openshift-images#encrypted-images

* Item 3 reads: 
`openssl genrsa --out myprivatekey.pem`

* Should be:
`openssl genrsa -out myprivatekey.pem`

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've updated this page in our internal source. The changes will reflect here with our prod promotion later today.
