### ISSUE TITLE
Format Error - Wrapped Key Instructions

### ISSUE THREAD

**Issue by ssalerno-ibmcloud** [ibm-cloud-docs/openshift#98]
YAML is misformatted in code block and will not work if copied as-is.

https://cloud.ibm.com/docs/openshift?topic=openshift-images#encrypted-images

Item "c" in wrap instructions. PR to follow.

**Comment by ssalerno-ibmcloud** [comment]
Fixed by #97

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've updated this page in our internal source. The changes will reflect here with our prod promotion later today.
