### ISSUE TITLE
Missing field in tailoredprofile.yaml

### ISSUE THREAD

**Issue by jachtermann** [ibm-cloud-docs/openshift#99]
In the instructions for the OpenShift compliance operator (https://cloud.ibm.com/docs/openshift?topic=openshift-compliance-operator). There seems to be a field missing in the sample tailoredprofile.yaml file (https://github.com/IBM-Cloud/kube-samples/blob/master/roks-compliance-operator/tailoredprofile.yaml). 

When running against OpenShift 4.7. I had to add a spec.description field in order to load it. Without it the "oc apply" command to load tailoredprofile.yaml gave me the following error message:

```
% oc apply -n openshift-compliance -f https://raw.githubusercontent.com/IBM-Cloud/kube-samples/master/roks-compliance-operator/tailoredprofile.yaml
The TailoredProfile "roks-cis-node" is invalid: spec.description: Required value
```

I added the following line to the tailoredprofile.yaml file:

```
  description: "IBM ROKS tailored scan"
```

This is line #8 in the attached file. I had to add the .txt file extension in order for GitHub to load it.

I have not looked at it closely enough to know if or how the behavior changes between OpenShift versions.

[tailoredprofile.yaml.txt](https://github.com/ibm-cloud-docs/openshift/files/7894072/tailoredprofile.yaml.txt)
.

**Comment by daniel-p-miller** [comment]
Jeff, thanks for your feedback! 

I have applied the change.
